language: ruby
rvm:
  - 2.4.1

script: 
  bundle exec jekyll build
  bundle exec htmlproofer ./_site

# # deploy:
#   provider: pages
#   skip-cleanup: true
#   local_dir: _site/
#   repo: gjbunyea/gjbunyea.github.io
#   target_branch: master
#   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: master